import { Component, VERSION, ElementRef, ViewChild, OnInit } from '@angular/core';

@Component({
  selector: 'app-test',
  templateUrl: './test.component.html',
  styleUrls: ['./test.component.scss'],
  queries: {
    'contentRef': new ViewChild('contentRef')
  }
})
export class TestComponent implements OnInit {
  ngOnInit(): void {
    setTimeout(() => {
      this.contentRef.nativeElement.scrollTo(0, this.contentRef.nativeElement.scrollHeight);

    }, 2000);

  }
  name: any = 'Angular ' + VERSION.major;
  content: any = '';
  postedContent: any = [
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',
    'asdasdas',

  ];
  contentRef!: ElementRef;
  contentHeight: any;

  addContent() {
    this.postedContent.push(this.content);
    this.content = '';
    this.contentHeight = this.contentRef.nativeElement.scrollHeight;
    this.contentRef.nativeElement.scrollTo(0, this.contentRef.nativeElement.scrollHeight);
  }

  ngAfterViewChecked() {
    // var test = this.contentHeight != this.contentRef.nativeElement.scrollHeight
    //&& this.contentRef.nativeElement.scrollHeight != (this.contentRef.nativeElement.scrollTop + this.contentRef.nativeElement.offsetHeight);
    // console.log(test);

    // if (this.contentHeight != this.contentRef.nativeElement.scrollHeight && this.contentRef.nativeElement.scrollHeight != (this.contentRef.nativeElement.scrollTop + this.contentRef.nativeElement.offsetHeight)) {
    // this.contentRef.nativeElement.scrollTo(0, this.contentRef.nativeElement.scrollHeight);
    // }
  }

}

